#!/usr/bin/env bash

if [ ! -f "$(pwd)/.bxwi_protobuf.locate" ]; then
    echo >&2 "[error] Please run from the Protobuf installer directory!"
    exit 1
fi
source $(pwd)/../lib/libbxiw.bash
bxiw_app_name="protobuf_installer"
bxiw_app_saved_opwd=$(pwd)
bxiw_app_installer_prefix="$(pwd)"
bxiw_package_name="protobuf"
#bxiw_default_package_version="3.3.0" // not supported
bxiw_default_package_version="3.7.1"
bxiw_package_version=

protobuf_with_java=false

function protobuf_installer_usage()
{
    cat<<EOF

protobuf_installer - Protobuf library installer

Synopsis:

    protobuf_installer [OPTION]...

Options:

  --help              Print this help then exit
EOF
    _bxiw_usage_options
#     cat<<EOF
#   --with-java         Build Protobuf Java interface
# EOF
     echo ""
    return 0
}


function protobuf_installer_parse_cl()
{
    while [ -n "$1" ]; do
	token="$1"
	if [ "x${token:0:1}" = "x-" ]; then
	    opt="${token}"
	    if [ ${opt} = "--help" ]; then
		protobuf_installer_usage
		bxiw_exit 0
	    # elif [ ${opt} = "--with-java" ]; then
	    # 	protobuf_with_java=true
	    else
		bxiw_log_error "Unsupported option '${opt}'!"
		return 1
	    fi
	else
	    arg="${token}"
	fi
	shift 1
    done
    return 0
}

function protobuf_installer_prepare()
{
    _bxiw_prepare_pre
 
    if [ ${bxiw_with_gui} = true ]; then
	
	local _do_rebuild_repr="FALSE"
	if [ ${bxiw_do_rebuild} = true ]; then
	    _do_rebuild_repr="TRUE"
	fi
	
	local _remove_build_dir_repr="FALSE"
	if [ ${bxiw_remove_build_dir} = true ]; then
	    _remove_build_dir_repr="TRUE"
	fi
	
	local _remove_tarballs_repr="FALSE"
	if [ ${bxiw_remove_tarballs} = true ]; then
	    _remove_tarballs_repr="TRUE"
	fi
	
	local _system_install_repr="FALSE"
	if [ ${bxiw_system_install} = true ]; then
	    _system_install_repr="TRUE"
	fi

	which yad > /dev/null 2>&1
	if [ $? -ne 0 ]; then
	    bxiw_message "[warning] yad is not installed! No GUI!"
	else
	    local _choices=$(yad --width=500 \
				 --form \
				 --title "${bxiw_package_name} installer options" \
				 --field="Cache directory:CDIR"   "${bxiw_cache_dir}" \
				 --field="Working directory:CDIR" "${bxiw_work_dir}" \
				 --field="Installation directory:CDIR" "${bxiw_install_dir}" \
				 --field="Force rebuild:CHK" "${_do_rebuild_repr}" \
				 --field="Remove build directory:CHK" "${_remove_build_dir_repr}" \
				 --field="Remove tarballs:CHK" "${_remove_tarballs_repr}" \
				 --field="System installation:CHK" "$_system_install_repr}" \
		  )
	    if [ "x${_choices}" = "x" ]; then
		bxiw_message "info" "Cancelled dialog!"
		return 1
	    fi
	    bxiw_cache_dir=$(echo ${_choices} | cut -d'|' -f1)
	    bxiw_work_dir=$(echo ${_choices} | cut -d'|' -f2)
	    bxiw_install_dir=$(echo ${_choices} | cut -d'|' -f3)
	    _do_rebuild_repr=$(echo ${_choices} | cut -d'|' -f4)
	    if [ ${_do_rebuild_repr} == "TRUE" ]; then
		bxiw_do_rebuild=true
	    else
		bxiw_do_rebuild=false
	    fi
	    _remove_build_dir_repr=$(echo ${_choices} | cut -d'|' -f5)
	    if [ ${_remove_build_dir_repr} == "TRUE" ]; then
		bxiw_remove_build_dir=true
	    else
		bxiw_remove_build_dir=false
	    fi
	    _remove_tarballs_repr=$(echo ${_choices} | cut -d'|' -f6)
	    if [ ${_remove_tarballs_repr} == "TRUE" ]; then
		bxiw_remove_tarballs=true
	    else
		bxiw_remove_tarballs=false
	    fi
	    _system_install_repr=$(echo ${_choices} | cut -d'|' -f7)
	    if [ ${_system_install_repr} == "TRUE" ]; then
		bxiw_system_install=true
	    else
		bxiw_system_install=false
	    fi
	fi
    fi

    # Boost:
    # if [ "x${boost_root}" = "x" ]; then
    # 	boost_root="/usr"
    # fi
    # bxiw_log_info "Use Boost installation dir : '${boost_root}'"
    
    # if [ "x${boost_root}" != "x" ]; then
    # 	if [ ! -f "${boost_root}/include/boost/version.hpp" ]; then
    # 	    bxiw_log_error "Cannot find '${boost_root}/include/boost/version.hpp' file!"
    # 	    return 1
    # 	fi
    # 	bxiw_pass
    # fi
    
    # Prepare:
    _bxiw_prepare_post
     
    return 0
}


function protobuf_installer_get_tarball()
{
    local _protobuf_version="$1"
    shift 1
    local _protobuf_lang="$1"
    shift 1
    # echo "protobuf-v${_protobuf_version}.tar.gz"
    echo "protobuf-${_protobuf_lang}-${_protobuf_version}.tar.gz"
    # Examples:
    #   protobuf-cpp-3.7.1.tar.gz
    #   protobuf-java-3.7.1.tar.gz
    return 0
}


function protobuf_installer_get_url()
{
    local _protobuf_version="$1"
    shift 1
    local _protobuf_lang="$1"
    shift 1
    local _protobuf_tarball=$(protobuf_installer_get_tarball ${_protobuf_version} ${_protobuf_lang})
    ### echo "https://github.com/google/protobuf/archive/${_protobuf_tarball}"
    echo "https://github.com/protocolbuffers/protobuf/releases/download/v${_protobuf_version}/${_protobuf_tarball}"
    return 0
}


function protobuf_installer_set_system_dependencies()
{
    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
	bxiw_system_packages_build="\
   	  	    autoconf \
		    automake \
		    libtool \
		    curl\
		    unzip \
   	  	    make \
        	    pkg-config \
        	    dpkg-dev \
       	    	    wget \
   		    g++ \
		    gcc \
		    "
	if [ ${bxiw_with_package} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} checkinstall"
	fi
	if [ ${bxiw_with_gui} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} yad"
	fi
	if [ ${protobuf_with_java} == true ]; then
	    if [ "x${bxiw_os_distrib_release}" = "x18.04" ]; then
		# bxiw_system_packages_build="${bxiw_system} default-jdk maven"
		bxiw_system_packages_build="${bxiw_system} openjdk-11-jdk maven"
	    else
		bxiw_system_packages_build="${bxiw_system} default-jdk maven"
	    fi	    
	fi
	bxiw_system_packages_run="g++ gcc"
	bxiw_pass
    elif [ "x${bxiw_os_distrib_id}" = "xCentOS" ]; then
	bxiw_pass
    elif [ "x${bxiw_os_distrib_id}" = "xScientific" ]; then
	bxiw_pass
    fi
    return 0
}


function protobuf_installer_print()
{
    bxiw_print
    return 0
}


function protobuf_installer_download()
{
    local _protobuf_tarball=$(protobuf_installer_get_tarball ${bxiw_package_version} "cpp")
    local _protobuf_url=$(protobuf_installer_get_url ${bxiw_package_version} "cpp")
    bxiw_log_info "Protobuf C++ tarball : '${_protobuf_tarball}'"
    bxiw_log_info "Protobuf URL     : '${_protobuf_url}'"
    if [ ! -f ${bxiw_tag_downloaded} ]; then
	bxiw_download_file ${_protobuf_url} ${_protobuf_tarball} 
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Could not download the '${_protobuf_tarball}' file!"
	    return 1
	fi
	if [ ${protobuf_with_java} == true ]; then
	    _protobuf_tarball=$(protobuf_installer_get_tarball ${bxiw_package_version} "java")
	    _protobuf_url=$(protobuf_installer_get_url ${bxiw_package_version} "java")
	    bxiw_log_info "Protobuf Java tarball : '${_protobuf_tarball}'"
	    bxiw_log_info "Protobuf URL     : '${_protobuf_url}'"
	    if [ ! -f ${bxiw_tag_downloaded} ]; then
		bxiw_download_file ${_protobuf_url} ${_protobuf_tarball} 
		if [ $? -ne 0 ]; then
		    bxiw_log_error "Could not download the '${_protobuf_tarball}' file!"
		    return 1
		fi
	    else
		bxiw_log_info "Protobuf tarball for Java language is already downloaded."
	    fi
	fi
	touch ${bxiw_tag_downloaded}
    else
	bxiw_log_info "Protobuf tarball(s) is/are already downloaded."
    fi
    return  0
}


function protobuf_installer_install()
{
    local _protobuf_opwd=$(pwd)
    local _protobuf_tarball=$(protobuf_installer_get_tarball ${bxiw_package_version} "cpp")
    cd ${bxiw_cache_dir}
    local _protobuf_source_dir="$(pwd)/protobuf-${bxiw_package_version}"
    bxiw_message "info" "Protobuf version is                : '${bxiw_package_version}'"
    bxiw_message "info" "Protobuf source directory is       : '${_protobuf_source_dir}'"
    if [ ! -d ${_protobuf_source_dir} ]; then
	bxiw_message "info" "Unpacking source directory..."
	tar xzf ${bxiw_cache_dir}/${_protobuf_tarball}
	if [ $? -ne 0 ]; then
	    bxiw_message "error" "Source directory has not been unpacked."
	    cd ${_protobuf_opwd}
	    return 1
	else
	    bxiw_message "info" "Source directory has been unpacked."
	fi
	if [ ${protobuf_with_java} == true ]; then
	    _protobuf_tarball_java=$(protobuf_installer_get_tarball ${bxiw_package_version} "java")
	    bxiw_message "info" "Unpacking source directory..."
	    tar xzf ${bxiw_cache_dir}/${_protobuf_tarball_java}
	    if [ $? -ne 0 ]; then
		bxiw_message "error" "Source directory for Java language has not been unpacked."
		cd ${_protobuf_opwd}
		return 1
	    else
		bxiw_message "info" "Source directory for Java language has been unpacked."
	    fi
	fi
    else
	bxiw_message "info" "Source directory was already unpacked."
    fi

    cd ${bxiw_build_dir}
    cp -a ${_protobuf_source_dir}/* . 
    bxiw_message "info" "Protobuf build directory is        : '${bxiw_build_dir}'"
    bxiw_message "info" "Protobuf tag directory is          : '${bxiw_tag_dir}'"
    bxiw_message "info" "Protobuf installation directory is : '${bxiw_install_dir}'"
    
    # Configuration:
    local _protobuf_do_config=false
    if [ ! -f ${bxiw_tag_configured} ]; then
	bxiw_message "info" "Protobuf configuration is needed."
	_protobuf_do_config=true
    else
	bxiw_message "info" "Protobuf configuration is already done."
	if [ ${bxiw_do_reconfigure} == true ]; then
	    bxiw_message "info" "Forcing Protobuf reconfiguration..."
	    _protobuf_do_configure=true
	fi
    fi

    if [ ${_protobuf_do_config} == true ]; then
	bxiw_message "info" "Protobuf configuration..."
	./autogen.sh
	if [ $? -ne 0 ]; then
	    bxiw_message "error" "Autogen failed!"
	    cd ${_protobuf_opwd}
	    return 1
	else
	    touch ${bxiw_tag_configured}
    	    bxiw_message "info" "Protobuf's autogen success."
	fi
	./configure \
	    --disable-debug \
	    --disable-dependency-tracking \
            --prefix="${bxiw_install_dir}" \
	    --with-zlib
	if [ $? -ne 0 ]; then
	    bxiw_message "error" "Protobuf configuration failed!"
	    cd ${_protobuf_opwd}
	    return 1
	else
	    touch ${bxiw_tag_configured}
    	    bxiw_message "info" "Protobuf is configured."
	fi
    else
	bxiw_message "info" "Do not configure Protobuf."
    fi
    
    # Build:
    local _protobuf_do_build=false
    if [ ! -f ${bxiw_tag_built} ]; then
	bxiw_message "info" "Protobuf build is needed."
	_protobuf_do_build=true
    else
	bxiw_message "info" "Protobuf build is already done."
	if [ ${bxiw_do_rebuild} == true ]; then
	    bxiw_message "info" "Forcing Protobuf rebuild..."
	    _protobuf_do_build=true
	fi
    fi

    if [ ${_protobuf_do_build} == true ]; then
	bxiw_message "info" "Building Protobuf..."
	local _protobuf_nbprocs=${bxiw_nbprocs}
	if [ ${_protobuf_nbprocs} -gt 2 ]; then
	    let _protobuf_nbprocs=${bxiw_nbprocs}
	else
	    _protobuf_nbprocs=1 
	fi
	bxiw_message "info" "#procs = ${_protobuf_nbprocs}"
	make -j ${_protobuf_nbprocs}
	if [ $? -ne 0 ]; then
    	    bxiw_message "error" "Protobuf build failed!"
    	    cd ${_protobuf_opwd}
    	    return 1
	else
	    touch ${bxiw_tag_built}
    	    bxiw_message "info" "Protobuf is built."
	fi
	
    else
	bxiw_message "info" "Do not build Protobuf."
    fi

    # Installation:
    local _protobuf_do_install=false
    if [ ! -f ${bxiw_tag_installed} ]; then
	bxiw_message "info" "Protobuf installation is needed."
	_protobuf_do_install=true
    else
	bxiw_message "info" "Protobuf installation is already done."
	if [ ${bxiw_do_reinstall} == true ]; then
	    _protobuf_do_install=true
	    bxiw_message "info" "Forcing Protobuf installation..."
	fi
    fi
    if [ ${bxiw_no_install} == true ]; then
	_protobuf_do_install=false
    fi

    if [ ${_protobuf_do_install} == true ]; then
	local _protobuf_do_package=false
	if [ ${bxiw_with_package} == true ]; then
	    _protobuf_do_package=true
	fi
	if [ ${_protobuf_do_package} == true ]; then
	    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
		bxiw_message "info" "Building a binary package for Protobuf..."
		protobuf_installer_makedebpack
	    else
    		bxiw_message "error" "Cannot pack Protobuf for '${bxiw_os_distrib_id}'!"
    		cd ${_protobuf_opwd}
		return 1
	    fi
	else
	    bxiw_message "info" "Installing Protobuf..."
	    make install
	    if [ $? -ne 0 ]; then
    		bxiw_message "error" "Protobuf installation failed!"
    		cd ${_protobuf_opwd}
    		return 1
	    else
		touch ${bxiw_tag_installed}
    		bxiw_message "info" "Protobuf is installed."
	    fi
	fi
    else
	bxiw_message "info" "Do not install Protobuf."
    fi

    if [ ${protobuf_with_java} == true ]; then
    	bxiw_log_info "Installing Protobuf Java..."
	export PATH="${bxiw_install_dir}/bin:${PATH}"
	cd ${bxiw_build_dir}/java
	# mvn test
	# if [ $? -ne 0 ]; then
    	#     bxiw_message "error" "Protobuf Java maven test failed!"
    	#     cd ${_protobuf_opwd}
    	#     return 1
	# else
	#     touch ${bxiw_tag_installed}
    	#     bxiw_message "info" "Protobuf Java maven test success."
	# fi
	# mvn install # -Dmaven.test.skip=true -DskipTests
	mvn install -Dmaven.test.skip=true
	if [ $? -ne 0 ]; then
    	    bxiw_message "error" "Protobuf Java maven install failed!"
    	    cd ${_protobuf_opwd}
    	    return 1
	else
	    touch ${bxiw_tag_installed}
    	    bxiw_message "info" "Protobuf Java maven install success."
	fi
	mvn package
	if [ $? -ne 0 ]; then
    	    bxiw_message "error" "Protobuf Java maven package failed!"
    	    cd ${_protobuf_opwd}
    	    return 1
	else
	    touch ${bxiw_tag_installed}
    	    bxiw_message "info" "Protobuf Java maven package success."
	fi
	mkdir -p ${bxiw_install_dir}/lib/java
	cp ./core/target/protobuf-java-${bxiw_package_version}.jar      ${bxiw_install_dir}/lib/java/
	cp ./core/target/protobuf-java-util-${bxiw_package_version}.jar ${bxiw_install_dir}/lib/java/
    fi
    
    cd ${_protobuf_opwd}
    return  0
}


function protobuf_installer_makedebpack()
{
    local _protobuf_build_dir="${bxiw_build_dir}"
    cd ${_protobuf_build_dir}
    mkdir -p ${_protobuf_build_dir}/doc-pak
    touch ${_protobuf_build_dir}/description-pak
    cat>${_protobuf_build_dir}/description-pak<<EOF
Protobuf (Bayeux edition)

This is a binary version for ${bxiw_os_distrib_id} ${bxiw_os_distrib_release} 
usable with the Bayeux software suite.
EOF
 
    local _arch="amd64"
    local _protobuf_do_package=true
    local _protobuf_pkg_filename="bx${bxiw_package_name}_${bxiw_package_version}-${bxiw_pkg_release}_${_arch}.deb"
    if [ -f ${package_dir}/${_protobuf_pkg_filename} ]; then
	bxiw_message "info" "Package '${_protobuf_pkg_filename}' exists in '${bxiw_package_dir}'."
	_protobuf_do_package=false
    fi
    local _protobuf_requires="\
		"
    _protobuf_requires_list=$(echo ${_protobuf_requires} | tr ' ' ',')
    _protobuf_conflicts_list="libprotobuf-dev,libprotobuf0.8"
    bxiw_message "info" "Requires : ${_protobuf_requires_list}!"	
    if [ ${_protobuf_do_package} == true ]; then
	if [ "x${bxiw_os_arch}" != "xx86_64" ]; then
	    bxiw_message "error" "Unsupported architecture ${bxiw_os_arch}!"	
	    return 1
	fi
	sudo checkinstall \
	     --type="debian" \
	     --install="no" \
	     --fstrans="no" \
	     --pkgname="bx${bxiw_package_name}" \
	     --pkgversion="${bxiw_package_version}" \
	     --pkgrelease=${bxiw_pkg_release} \
	     --pkglicense="MIT" \
	     --pkgsource="$(protobuf_installer_get_url ${bxiw_package_version})" \
	     --maintainer="${bxiw_pkg_maintener_email}" \
	     --provides="bx${bxiw_package_name}" \
	     --requires="${_protobuf_requires_list}" \
	     --conflicts="${_protobuf_conflicts_list}" \
	     --backup="no" \
	     --pakdir="${bxiw_package_dir}" \
	     --default \
	     ninja install
	if [ $? -ne 0 ]; then
	    bxiw_message "error" "Debian binary package build failed!"	
	    return 1
	fi
    fi	 
    return 0
}


function protobuf_installer_setup()
{
    bxiw_log_trace "protobuf_installer_setup: entering..."
    local _bxsoftware_setup_dir="${bxiw_setup_module_dir}"
    local _bxsoftware_setup_script="${_bxsoftware_setup_dir}/${bxiw_package_name}@${bxiw_package_version}.bash"
    local _bxsoftware_underscored_version=$(bxiw_underscored_version ${bxiw_package_version})
    bxiw_message "info" "Installing setup script '${_bxsoftware_setup_script}'..."
    cat ${bxiw_app_installer_prefix}/resources/${bxiw_package_name}.bash.in | \
	sed \
	    -e "s@__PROTOBUF_INSTALL_DIR__@${bxiw_install_dir}@g" \
	    -e "s@__PROTOBUF_VERSION__@${bxiw_package_version}@g" \
            -e "s@__PROTOBUF_UVERSION__@${_bxsoftware_underscored_version}@g" \
	    > ${_bxsoftware_setup_script}
    return  0
}

bxiw_detect_os
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Unsupported OS!"
fi

bxiw_env
bxiw_parse_cl ${bxiw_app_cl_remaining_argv}
bxiw_message "info" "bxiw_app_cl_remaining_argv=${bxiw_app_cl_remaining_argv}"
protobuf_installer_parse_cl ${bxiw_app_cl_remaining_argv}
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Command line parse error!"
fi

protobuf_installer_prepare
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Preparation failed!"
fi

protobuf_installer_set_system_dependencies

protobuf_installer_print

bxiw_install_system_dependencies
if [ $? -ne 0 ]; then
    bxiw_exit 1 "System dependencies installation failed!"
fi

protobuf_installer_download
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Source archive download failed!"
fi

protobuf_installer_install
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Installation failed!"
fi

if [ ${bxiw_with_package} == false ]; then
    protobuf_installer_setup
    if [ $? -ne 0 ]; then
	bxiw_exit 1 "Setup failed!"
    fi
fi

bxiw_exit 0

# end
