#!/usr/bin/env bash

if [ ! -f "$(pwd)/.bxwi_clhep.locate" ]; then
    echo >&2 "[error] Please run from the CLHEP installer directory!"
    exit 1
fi
source $(pwd)/../lib/libbxiw.bash
bxiw_app_name="clhep_installer"
bxiw_app_saved_opwd=$(pwd)
bxiw_app_installer_prefix="$(pwd)"
bxiw_package_name="clhep"
bxiw_default_package_version="2.4.5.1"
bxiw_supported_package_versions="2.1.3.1 2.1.4.2 2.4.1.0 2.4.4.0 2.4.5.1"
bxiw_package_version=
use_ninja=true
ninja_exe=
build_bin=


function clhep_installer_usage()
{
    cat<<EOF

clhep_installer - CLHEP library installer

Synopsis:

    clhep_installer [OPTION]...

Options:

  --help              Print this help then exit
EOF
    _bxiw_usage_options
   cat<<EOF
  --ninja-exe         Set Ninja executable path
  --no-ninja          Do not use Ninja
EOF
    echo ""
    return 0
}


function clhep_installer_parse_cl()
{
    ### echo >&2 "[devel] clhep_installer_parse_cl: restart argv='$@'"
    while [ -n "$1" ]; do
	token="$1"
	if [ "x${token:0:1}" = "x-" ]; then
	    opt="${token}"
	    if [ ${opt} = "--help" ]; then
		clhep_installer_usage
		bxiw_exit 0
	    elif [ ${opt} = "--ninja-exe" ]; then
		shift 1
		ninja_exe=$1
	    elif [ ${opt} = "--no-ninja" ]; then
		use_ninja=false
	    else
		bxiw_log_error "Unsupported option '${opt}'!"
		return 1
	    fi
	else
	    arg="${token}"
	fi
	shift 1
    done
    return 0
}

function clhep_installer_prepare()
{
    _bxiw_prepare_pre
 
    if [ ${bxiw_with_gui} = true ]; then
	
	local _do_rebuild_repr="FALSE"
	if [ ${bxiw_do_rebuild} = true ]; then
	    _do_rebuild_repr="TRUE"
	fi
	
	local _remove_build_dir_repr="FALSE"
	if [ ${bxiw_remove_build_dir} = true ]; then
	    _remove_build_dir_repr="TRUE"
	fi
	
	local _remove_tarballs_repr="FALSE"
	if [ ${bxiw_remove_tarballs} = true ]; then
	    _remove_tarballs_repr="TRUE"
	fi
	
	local _system_install_repr="FALSE"
	if [ ${bxiw_system_install} = true ]; then
	    _system_install_repr="TRUE"
	fi

	which yad > /dev/null 2>&1
	if [ $? -ne 0 ]; then
	    bxiw_message "[warning] yad is not installed! No GUI!"
	else
	    local _choices=$(yad --width=500 \
				 --form \
				 --title "${bxiw_package_name} installer options" \
				 --field="Cache directory:CDIR"   "${bxiw_cache_dir}" \
				 --field="Working directory:CDIR" "${bxiw_work_dir}" \
				 --field="Installation directory:CDIR" "${bxiw_install_dir}" \
				 --field="Force rebuild:CHK" "${_do_rebuild_repr}" \
				 --field="Remove build directory:CHK" "${_remove_build_dir_repr}" \
				 --field="Remove tarballs:CHK" "${_remove_tarballs_repr}" \
				 --field="System installation:CHK" "$_system_install_repr}" \
		  )
	    if [ "x${_choices}" = "x" ]; then
		bxiw_log_info "Cancelled dialog!"
		return 1
	    fi
	    bxiw_cache_dir=$(echo ${_choices} | cut -d'|' -f1)
	    bxiw_work_dir=$(echo ${_choices} | cut -d'|' -f2)
	    bxiw_install_dir=$(echo ${_choices} | cut -d'|' -f3)
	    _do_rebuild_repr=$(echo ${_choices} | cut -d'|' -f4)
	    if [ ${_do_rebuild_repr} == "TRUE" ]; then
		bxiw_do_rebuild=true
	    else
		bxiw_do_rebuild=false
	    fi
	    _remove_build_dir_repr=$(echo ${_choices} | cut -d'|' -f5)
	    if [ ${_remove_build_dir_repr} == "TRUE" ]; then
		bxiw_remove_build_dir=true
	    else
		bxiw_remove_build_dir=false
	    fi
	    _remove_tarballs_repr=$(echo ${_choices} | cut -d'|' -f6)
	    if [ ${_remove_tarballs_repr} == "TRUE" ]; then
		bxiw_remove_tarballs=true
	    else
		bxiw_remove_tarballs=false
	    fi
	    _system_install_repr=$(echo ${_choices} | cut -d'|' -f7)
	    if [ ${_system_install_repr} == "TRUE" ]; then
		bxiw_system_install=true
	    else
		bxiw_system_install=false
	    fi
	fi
    fi
    
    # Prepare:
    _bxiw_prepare_post
     
    return 0
}


function clhep_installer_get_tarball()
{
    local _clhep_version="$1"
    shift 1
    echo "clhep-${_clhep_version}.tgz"
    return 0
}


function clhep_installer_get_url()
{
    local _clhep_version="$1"
    local _clhep_tarball=$(clhep_installer_get_tarball ${_clhep_version})
    if [ "${_clhep_version}" == "2.4.4.0" ]; then
	echo " https://proj-clhep.web.cern.ch/proj-clhep/dist1/clhep-2.4.4.0.tgz"
    elif [ "${_clhep_version}" == "2.4.5.1" ]; then
	echo " https://proj-clhep.web.cern.ch/proj-clhep/dist1/clhep-2.4.5.1.tgz"
    else
	echo "http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/${_clhep_tarball}"
    fi
    return 0
}


function clhep_installer_set_system_dependencies()
{
    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
	bxiw_system_packages_build="cmake \
   	  	    ninja-build \
   	  	    make \
        	    pkg-config \
        	    dpkg-dev \
       	    	    wget \
   		    g++ \
		    gcc \
		    doxygen \
		    texlive-latex-base \
		    "
	if [ ${bxiw_with_package} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} checkinstall"
	fi
	if [ ${bxiw_with_gui} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} yad"
	fi
	# if [ "x${bxiw_os_distrib_release}" = "x18.04" ]; then
	    
	# fi
	bxiw_system_packages_run=""
    # elif [ "x${bxiw_os_distrib_id}" = "xCentOS" ]; then
    # elif [ "x${bxiw_os_distrib_id}" = "xScientific" ]; then
    fi
    return 0
}


function clhep_installer_print()
{
    bxiw_print
    return 0
}


function clhep_installer_download()
{
    local _clhep_tarball=$(clhep_installer_get_tarball ${bxiw_package_version})
    local _clhep_url=$(clhep_installer_get_url ${bxiw_package_version})
    bxiw_download_file ${_clhep_url} ${_clhep_tarball}
    if [ $? -ne 0 ]; then
	bxiw_log_error "Could not download the '${_clhep_tarball}' file!"
	return 1
    fi
    return  0
}


function clhep_installer_install()
{
    local _clhep_opwd=$(pwd)
    local _clhep_tarball=$(clhep_installer_get_tarball ${bxiw_package_version})
    cd ${bxiw_cache_dir}
    local _clhep_source_dir="$(pwd)/${bxiw_package_version}/CLHEP"
    bxiw_log_info "CLHEP version is                : '${bxiw_package_version}'"
    bxiw_log_info "CLHEP source directory is       : '${_clhep_source_dir}'"
    if [ ! -d ${_clhep_source_dir} ]; then
	bxiw_log_info "Unpacking source directory..."
	tar xzf ${bxiw_cache_dir}/${_clhep_tarball}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Source directory has not been unpacked."
	    cd ${_clhep_opwd}
	    return 1
	else
	    bxiw_log_info "Source directory has been unpacked."
	fi
    else
	bxiw_log_info "Source directory was already unpacked."
    fi

    cd ${bxiw_build_dir}
    bxiw_log_info "CLHEP build directory is        : '${bxiw_build_dir}'"
    bxiw_log_info "CLHEP tag directory is          : '${bxiw_tag_dir}'"
    bxiw_log_info "CLHEP installation directory is : '${bxiw_install_dir}'"
    
    # Configuration:
    local _clhep_do_config=false
    if [ ! -f ${bxiw_tag_configured} ]; then
	bxiw_log_info "CLHEP configuration is needed."
	_clhep_do_config=true
    else
	bxiw_log_info "CLHEP configuration is already done."
	if [ ${bxiw_do_reconfigure} == true ]; then
	    bxiw_log_info "Forcing CLHEP reconfiguration..."
	    _clhep_do_configure=true
	fi
    fi

    ninja_options=
    build_bin=make
    if [ ${use_ninja} = true ]; then
	ninja_options="-G Ninja"
	build_bin=ninja
	if [ "x${ninja_exe}" != "x" ]; then
	    build_bin=${ninja_exe}
	    ninja_options="${ninja_options} -DCMAKE_MAKE_PROGRAM=ninja"
	fi
    fi

    if [ ${_clhep_do_config} == true ]; then
	cxxstd_option=
	if [ "${bxiw_package_version}" == "2.4.1.0" ]; then
	   cxxstd_option="-DCLHEP_BUILD_CXXSTD=-std=c++11"
	fi
	docs_option="-DCLHEP_BUILD_DOCS=OFF"
	###	    -DCLHEP_BUILD_DOCS=ON 
	bxiw_log_info "CLHEP configuration..."
	cmake  \
	    -DCMAKE_INSTALL_PREFIX:PATH="${bxiw_install_dir}" \
	    ${cxxstd_option} \
	    ${docs_option} \
	    ${ninja_options} \
	    ${_clhep_source_dir}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "CLHEP configuration failed!"
	    cd ${_clhep_opwd}
	    return 1
	else
	    touch ${bxiw_tag_configured}
    	    bxiw_log_info "CLHEP is configured."
	fi
    else
	bxiw_log_info "Do not configure CLHEP."
    fi
    
    # Build:
    local _clhep_do_build=false
    if [ ! -f ${bxiw_tag_built} ]; then
	bxiw_log_info "CLHEP build is needed."
	_clhep_do_build=true
    else
	bxiw_log_info "CLHEP build is already done."
	if [ ${bxiw_do_rebuild} == true ]; then
	    bxiw_log_info "Forcing CLHEP rebuild..."
	    _clhep_do_build=true
	fi
    fi

    if [ ${_clhep_do_build} == true ]; then
	bxiw_log_info "Building CLHEP..."
	local _clhep_nbprocs=${bxiw_nbprocs}
	if [ ${_clhep_nbprocs} -gt 2 ]; then
	    let _clhep_nbprocs=${bxiw_nbprocs}
	else
	    _clhep_nbprocs=1 
	fi
	bxiw_log_info "#procs = ${_clhep_nbprocs}"
	${build_bin} -j ${_clhep_nbprocs}
	if [ $? -ne 0 ]; then
    	    bxiw_log_error "CLHEP build failed!"
    	    cd ${_clhep_opwd}
    	    return 1
	else
	    touch ${bxiw_tag_built}
    	    bxiw_log_info "CLHEP is built."
	fi
    else
	bxiw_log_info "Do not build CLHEP."
    fi

    # Installation:
    local _clhep_do_install=false
    if [ ! -f ${bxiw_tag_installed} ]; then
	bxiw_log_info "CLHEP installation is needed."
	_clhep_do_install=true
    else
	bxiw_log_info "CLHEP installation is already done."
	if [ ${bxiw_do_reinstall} == true ]; then
	    _clhep_do_install=true
	    bxiw_log_info "Forcing CLHEP installation..."
	fi
    fi
    if [ ${bxiw_no_install} == true ]; then
	_clhep_do_install=false
    fi

    if [ ${_clhep_do_install} == true ]; then
	local _clhep_do_package=false
	if [ ${bxiw_with_package} == true ]; then
	    _clhep_do_package=true
	fi
	if [ ${_clhep_do_package} == true ]; then
	    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
		bxiw_log_info "Building a binary package for CLHEP..."
		clhep_installer_makedebpack
	    else
    		bxiw_log_error "Cannot pack CLHEP for '${bxiw_os_distrib_id}'!"
    		cd ${_clhep_opwd}
		return 1
	    fi
	else
	    bxiw_log_info "Installing CLHEP..."
	    ${build_bin} install
	    if [ $? -ne 0 ]; then
    		bxiw_log_error "CLHEP installation failed!"
    		cd ${_clhep_opwd}
    		return 1
	    else
		touch ${bxiw_tag_installed}
    		bxiw_log_info "CLHEP is installed."
	    fi
	fi
    else
	bxiw_log_info "Do not install CLHEP."
    fi
    cd ${_clhep_opwd}
    return  0
}


function clhep_installer_makedebpack()
{
    local _clhep_build_dir="${bxiw_build_dir}"
    cd ${_clhep_build_dir}
    mkdir -p ${_clhep_build_dir}/doc-pak
    touch ${_clhep_build_dir}/description-pak
    cat>${_clhep_build_dir}/description-pak<<EOF
CLHEP C++ Class Library for High Energy Physics (Bayeux edition)

This is a binary version for ${bxiw_os_distrib_id} ${bxiw_os_distrib_release} 
usable with the Bayeux software suite and the Geant4 Toolkit.
EOF
 
    local _arch="amd64"
    local _clhep_do_package=true
    local _clhep_pkg_filename="bx${bxiw_package_name}_${bxiw_package_version}-${bxiw_pkg_release}_${_arch}.deb"
    if [ -f ${package_dir}/${_clhep_pkg_filename} ]; then
	bxiw_log_info "Package '${_clhep_pkg_filename}' exists in '${bxiw_package_dir}'."
	_clhep_do_package=false
    fi
    local _clhep_requires="\
		"
    _clhep_requires_list=$(echo ${_clhep_requires} | tr ' ' ',')
    _clhep_conflicts_list="libclhep-dev,libclhep2.1v5"
    bxiw_log_info "Requires : ${_clhep_requires_list}!"	
    if [ ${_clhep_do_package} == true ]; then
	if [ "x${bxiw_os_arch}" != "xx86_64" ]; then
	    bxiw_log_error "Unsupported architecture ${bxiw_os_arch}!"	
	    return 1
	fi
	sudo checkinstall \
	     --type="debian" \
	     --install="no" \
	     --fstrans="no" \
	     --pkgname="bx${bxiw_package_name}" \
	     --pkgversion="${bxiw_package_version}" \
	     --pkgrelease=${bxiw_pkg_release} \
	     --pkglicense="GPL-3" \
	     --pkgsource="$(clhep_installer_get_url ${bxiw_package_version})" \
	     --maintainer="${bxiw_pkg_maintener_email}" \
	     --provides="bx${bxiw_package_name}" \
	     --requires="${_clhep_requires_list}" \
	     --conflicts="${_clhep_conflicts_list}" \
	     --backup="no" \
	     --pakdir="${bxiw_package_dir}" \
	     --default \
	     ninja install
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Debian binary package build failed!"	
	    return 1
	fi
    fi	 
    return 0
}


function clhep_installer_setup()
{
    bxiw_log_trace "clhep_installer_setup: entering..."
    local _bxsoftware_setup_dir="${bxiw_setup_module_dir}"
    local _bxsoftware_setup_script_base="${_bxsoftware_setup_dir}/${bxiw_package_name}@${bxiw_package_version}.bash"
    local _bxsoftware_setup_script="${_bxsoftware_setup_script_base}"
    if [ -f ${_bxsoftware_setup_script} ]; then
	cp -f ${_bxsoftware_setup_script} ${_bxsoftware_setup_script}-save$(date -Isecond)
    fi
    # let num=1
    # while [ ! -f ${_bxsoftware_setup_script} ]; do
    # 	_bxsoftware_setup_script="${_bxsoftware_setup_script_base}-v${_num}"
    # 	let num=num+1
    # done
    local _bxsoftware_underscored_version=$(bxiw_underscored_version ${bxiw_package_version})
    bxiw_log_info "Installing setup script '${_bxsoftware_setup_script}'..."
    cat ${bxiw_app_installer_prefix}/resources/${bxiw_package_name}.bash.in | \
	sed \
	    -e "s@__CLHEP_INSTALL_DIR__@${bxiw_install_dir}@g" \
	    -e "s@__CLHEP_VERSION__@${bxiw_package_version}@g" \
	    -e "s@__CLHEP_UVERSION__@${_bxsoftware_underscored_version}@g" \
	    > ${_bxsoftware_setup_script}
    return  0
}

bxiw_detect_os
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Unsupported OS!"
fi

bxiw_env
bxiw_parse_cl ${bxiw_app_cl_remaining_argv}
# bxiw_log_info "bxiw_app_cl_remaining_argv=${bxiw_app_cl_remaining_argv}"
clhep_installer_parse_cl ${bxiw_app_cl_remaining_argv}
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Command line parse error!"
fi

clhep_installer_prepare
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Preparation failed!"
fi

clhep_installer_set_system_dependencies

clhep_installer_print

bxiw_install_system_dependencies
if [ $? -ne 0 ]; then
    bxiw_exit 1 "System dependencies installation failed!"
fi

clhep_installer_download
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Source archive download failed!"
fi

clhep_installer_install
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Installation failed!"
fi

if [ ${bxiw_with_package} == false ]; then
    clhep_installer_setup
    if [ $? -ne 0 ]; then
	bxiw_exit 1 "Setup failed!"
    fi
fi

bxiw_exit 0

# end
