#!/usr/bin/env bash

if [ ! -f "$(pwd)/.bxwi_bxjsontools.locate" ]; then
    echo >&2 "[error] Please run from the BxJsontools installer directory!"
    exit 1
fi
source $(pwd)/../lib/libbxiw.bash
bxiw_app_name="bxjsontools_installer"
bxiw_app_saved_opwd=$(pwd)
bxiw_app_installer_prefix="$(pwd)"
bxiw_package_name="bxjsontools"
bxiw_default_package_version="1.0.0"
bxiw_supported_package_versions="0.3.0 1.0.0"
bxiw_package_version=

boost_root=
use_ninja=true

function bxjsontools_installer_usage()
{
    cat<<EOF

bxjsontools_installer - BxJsontools library installer

Synopsis:

    bxjsontools_installer [OPTION]...

Options:

  --help               Print this help then exit
EOF
    _bxiw_usage_options
    cat<<EOF
  --boost-root path    Set the Boost installation path
  --no-ninja           Do not use Ninja
EOF
    echo ""
    return 0
}


function bxjsontools_installer_parse_cl()
{
    while [ -n "$1" ]; do
	token="$1"
	if [ "x${token:0:1}" = "x-" ]; then
	    opt="${token}"
	    if [ ${opt} = "--help" ]; then
		bxjsontools_installer_usage
		bxiw_exit 0
	    elif [ ${opt} = "--boost-root" ]; then
		shift 1
		boost_root="$1"
	    elif [ ${opt} = "--no-ninja" ]; then
		use_ninja=false
	    else
		bxiw_log_error "Unsupported option '${opt}'!"
		return 1
	    fi
	else
	    arg="${token}"
	fi
	shift 1
    done
    return 0
}

function bxjsontools_installer_prepare()
{
    _bxiw_prepare_pre
 
    if [ ${bxiw_with_gui} = true ]; then
	
	local _do_rebuild_repr="FALSE"
	if [ ${bxiw_do_rebuild} = true ]; then
	    _do_rebuild_repr="TRUE"
	fi
	
	local _remove_build_dir_repr="FALSE"
	if [ ${bxiw_remove_build_dir} = true ]; then
	    _remove_build_dir_repr="TRUE"
	fi
	
	local _remove_tarballs_repr="FALSE"
	if [ ${bxiw_remove_tarballs} = true ]; then
	    _remove_tarballs_repr="TRUE"
	fi
	
	local _system_install_repr="FALSE"
	if [ ${bxiw_system_install} = true ]; then
	    _system_install_repr="TRUE"
	fi

	which yad > /dev/null 2>&1
	if [ $? -ne 0 ]; then
	    bxiw_message "[warning] yad is not installed! No GUI!"
	else
	    local _choices=$(yad --width=500 \
				 --form \
				 --title "${bxiw_package_name} installer options" \
				 --field="Cache directory:CDIR"   "${bxiw_cache_dir}" \
				 --field="Working directory:CDIR" "${bxiw_work_dir}" \
				 --field="Installation directory:CDIR" "${bxiw_install_dir}" \
				 --field="Force rebuild:CHK" "${_do_rebuild_repr}" \
				 --field="Remove build directory:CHK" "${_remove_build_dir_repr}" \
				 --field="Remove tarballs:CHK" "${_remove_tarballs_repr}" \
				 --field="System installation:CHK" "$_system_install_repr}" \
		  )
	    if [ "x${_choices}" = "x" ]; then
		bxiw_log_error "Cancelled dialog!"
		return 1
	    fi
	    bxiw_cache_dir=$(echo ${_choices} | cut -d'|' -f1)
	    bxiw_work_dir=$(echo ${_choices} | cut -d'|' -f2)
	    bxiw_install_dir=$(echo ${_choices} | cut -d'|' -f3)
	    _do_rebuild_repr=$(echo ${_choices} | cut -d'|' -f4)
	    if [ ${_do_rebuild_repr} == "TRUE" ]; then
		bxiw_do_rebuild=true
	    else
		bxiw_do_rebuild=false
	    fi
	    _remove_build_dir_repr=$(echo ${_choices} | cut -d'|' -f5)
	    if [ ${_remove_build_dir_repr} == "TRUE" ]; then
		bxiw_remove_build_dir=true
	    else
		bxiw_remove_build_dir=false
	    fi
	    _remove_tarballs_repr=$(echo ${_choices} | cut -d'|' -f6)
	    if [ ${_remove_tarballs_repr} == "TRUE" ]; then
		bxiw_remove_tarballs=true
	    else
		bxiw_remove_tarballs=false
	    fi
	    _system_install_repr=$(echo ${_choices} | cut -d'|' -f7)
	    if [ ${_system_install_repr} == "TRUE" ]; then
		bxiw_system_install=true
	    else
		bxiw_system_install=false
	    fi
	fi
    fi

    # # XXX:
    # if [ "x${xxx_root}" = "x" ]; then
    # 	which xxx-config 2>&1 > /dev/null
    # 	if [ $? -eq 0 ]; then
    # 	    xxx_root="$(xxx-config --prefix)"
    # 	else
    # 	    xxx_root="/usr"
    # 	fi
    # fi
    # bxiw_log_info "Use XXX installation dir : '${xxx_root}'"
    
    # if [ "x${xxx_root}" != "x" ]; then
    # 	if [ ! -f "${xxx_root}/include/xxx/xxx_version.h" ]; then
    # 	    bxiw_log_error "Cannot find '${xxx_root}/include/xxx/xxx_version.h' file!"
    # 	    return 1
    # 	fi
    # 	bxiw_pass
    # fi
    
    # Prepare:
    _bxiw_prepare_post
     
    return 0
}


function bxjsontools_installer_get_tarball()
{
    local _bxjsontools_version="$1"
    shift 1
    echo "bxjsontools-${_bxjsontools_version}.tar.gz"
    return 0
}


function bxjsontools_installer_get_url()
{
    local _bxjsontools_version="$1"
    local _bxjsontools_tarball=$(bxjsontools_installer_get_tarball ${_bxjsontools_version})
    ### echo "https://github.com/tegesoft/bxjsontools/archive/${_bxjsontools_version}.tar.gz"
    ### echo "https://github.com/fw4spl-org/bxjsontools/archive/${_bxjsontools_version}.tar.gz"
    echo "https://github.com/BxCppDev/bxjsontools/archive/${_bxjsontools_version}.tar.gz"
    ### https://github.com/IRCAD-IHU/bxjsontools
    return 0
}


function bxjsontools_installer_set_system_dependencies()
{
    
    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
	bxiw_system_packages_build="cmake \
        	    pkg-config \
        	    dpkg-dev \
       	    	    wget \
   		    g++ \
		    gcc \
		    libboost-all-dev \
		    "
	if [ ${use_ninja} = true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} ninja-build"
	else
	    bxiw_system_packages_build="${bxiw_system_packages_build} make"
	fi
	if [ ${bxiw_with_package} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} checkinstall"
	fi
	if [ ${bxiw_with_gui} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} yad"
	fi
	# if [ "x${bxiw_os_distrib_release}" = "x18.04" ]; then
	    
	# fi
	bxiw_system_packages_run="g++ gcc"
	bxiw_pass
    elif [ "x${bxiw_os_distrib_id}" = "xCentOS" ]; then
	bxiw_pass
    elif [ "x${bxiw_os_distrib_id}" = "xScientific" ]; then
	bxiw_pass
    fi
    return 0
}


function bxjsontools_installer_print()
{
    bxiw_print
    return 0
}


function bxjsontools_installer_download()
{
    local _bxjsontools_tarball=$(bxjsontools_installer_get_tarball ${bxiw_package_version})
    local _bxjsontools_url=$(bxjsontools_installer_get_url ${bxiw_package_version})
    bxiw_log_info "BxJsontools tarball : '${_bxjsontools_tarball}'"
    bxiw_log_info "BxJsontools URL     : '${_bxjsontools_url}'"
    if [ ! -f ${bxiw_tag_downloaded} ]; then
	bxiw_download_file ${_bxjsontools_url} ${_bxjsontools_tarball}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Could not download the '${_bxjsontools_tarball}' file!"
	    return 1
	fi
	touch ${bxiw_tag_downloaded}
    else
	bxiw_log_info "BxJsontools tarball is already downloaded."
    fi
    return  0
}


function bxjsontools_installer_install()
{
    local _bxjsontools_opwd=$(pwd)
    local _bxjsontools_tarball=$(bxjsontools_installer_get_tarball ${bxiw_package_version})
    cd ${bxiw_cache_dir}
    local _bxjsontools_source_dir="$(pwd)/bxjsontools-${bxiw_package_version}"
    bxiw_log_info "BxJsontools version is                : '${bxiw_package_version}'"
    bxiw_log_info "BxJsontools source directory is       : '${_bxjsontools_source_dir}'"
    if [ ! -d ${_bxjsontools_source_dir} ]; then
	bxiw_log_info "Unpacking source directory..."
	tar xzf ${bxiw_cache_dir}/${_bxjsontools_tarball}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Source directory has not been unpacked."
	    cd ${_bxjsontools_opwd}
	    return 1
	else
	    bxiw_log_info "Source directory has been unpacked."
	fi
    else
	bxiw_log_info "Source directory was already unpacked."
    fi

    cd ${bxiw_build_dir}
    bxiw_log_info "BxJsontools build directory is        : '${bxiw_build_dir}'"
    bxiw_log_info "BxJsontools tag directory is          : '${bxiw_tag_dir}'"
    bxiw_log_info "BxJsontools installation directory is : '${bxiw_install_dir}'"
    
    # Configuration:
    local _bxjsontools_do_config=false
    if [ ! -f ${bxiw_tag_configured} ]; then
	bxiw_log_info "BxJsontools configuration is needed."
	_bxjsontools_do_config=true
    else
	bxiw_log_info "BxJsontools configuration is already done."
	if [ ${bxiw_do_reconfigure} == true ]; then
	    bxiw_log_info "Forcing BxJsontools reconfiguration..."
	    _bxjsontools_do_configure=true
	fi
    fi

    ninja_options=
    build_bin=make
    if [ ${use_ninja} = true ]; then
	ninja_options="-G Ninja"
	build_bin=ninja
    fi
    
    if [ ${_bxjsontools_do_config} == true ]; then
	bxiw_log_info "BxJsontools configuration..."
	boost_opt=
	if [ "x${boost_root}" != "x" ]; then
	    boost_opt="-DBOOST_ROOT:PATH=${boost_root}"
	fi
	cmake \
	    -DCMAKE_INSTALL_PREFIX:PATH="${bxiw_install_dir}" \
	    ${boost_opt} \
	    ${ninja_options} \
	    ${_bxjsontools_source_dir}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "BxJsontools configuration failed!"
	    cd ${_bxjsontools_opwd}
	    return 1
	else
	    touch ${bxiw_tag_configured}
    	    bxiw_log_info "BxJsontools is configured."
	fi
    else
	bxiw_log_info "Do not configure BxJsontools."
    fi
    
    # Build:
    local _bxjsontools_do_build=false
    if [ ! -f ${bxiw_tag_built} ]; then
	bxiw_log_info "BxJsontools build is needed."
	_bxjsontools_do_build=true
    else
	bxiw_log_info "BxJsontools build is already done."
	if [ ${bxiw_do_rebuild} == true ]; then
	    bxiw_log_info "Forcing BxJsontools rebuild..."
	    _bxjsontools_do_build=true
	fi
    fi

    if [ ${_bxjsontools_do_build} == true ]; then
	bxiw_log_info "Building BxJsontools..."
	local _bxjsontools_nbprocs=${bxiw_nbprocs}
	if [ ${_bxjsontools_nbprocs} -gt 2 ]; then
	    let _bxjsontools_nbprocs=${bxiw_nbprocs}
	else
	    _bxjsontools_nbprocs=1 
	fi
	bxiw_log_info "#procs = ${_bxjsontools_nbprocs}"
	${build_bin} -j ${_bxjsontools_nbprocs}
	if [ $? -ne 0 ]; then
    	    bxiw_log_error "BxJsontools build failed!"
    	    cd ${_bxjsontools_opwd}
    	    return 1
	else
	    touch ${bxiw_tag_built}
    	    bxiw_log_info "BxJsontools is built."
	fi
    else
	bxiw_log_info "Do not build BxJsontools."
    fi

    # Installation:
    local _bxjsontools_do_install=false
    if [ ! -f ${bxiw_tag_installed} ]; then
	bxiw_log_info "BxJsontools installation is needed."
	_bxjsontools_do_install=true
    else
	bxiw_log_info "BxJsontools installation is already done."
	if [ ${bxiw_do_reinstall} == true ]; then
	    _bxjsontools_do_install=true
	    bxiw_log_info "Forcing BxJsontools installation..."
	fi
    fi
    if [ ${bxiw_no_install} == true ]; then
	_bxjsontools_do_install=false
    fi

    if [ ${_bxjsontools_do_install} == true ]; then
	local _bxjsontools_do_package=false
	if [ ${bxiw_with_package} == true ]; then
	    _bxjsontools_do_package=true
	fi
	if [ ${_bxjsontools_do_package} == true ]; then
	    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
		bxiw_log_info "Building a binary package for BxJsontools..."
		bxjsontools_installer_makedebpack
	    else
    		bxiw_log_error "Cannot pack BxJsontools for '${bxiw_os_distrib_id}'!"
    		cd ${_bxjsontools_opwd}
		return 1
	    fi
	else
	    bxiw_log_info "Installing BxJsontools..."
	    ${build_bin} install
	    if [ $? -ne 0 ]; then
    		bxiw_log_error "BxJsontools installation failed!"
    		cd ${_bxjsontools_opwd}
    		return 1
	    else
		touch ${bxiw_tag_installed}
    		bxiw_log_info "BxJsontools is installed."
	    fi
	fi
    else
	bxiw_log_info "Do not install BxJsontools."
    fi
    cd ${_bxjsontools_opwd}
    return  0
}


function bxjsontools_installer_makedebpack()
{
    local _bxjsontools_build_dir="${bxiw_build_dir}"
    cd ${_bxjsontools_build_dir}
    mkdir -p ${_bxjsontools_build_dir}/doc-pak
    touch ${_bxjsontools_build_dir}/description-pak
    cat>${_bxjsontools_build_dir}/description-pak<<EOF
BxJsontools C++ Library (Bayeux edition)

This is a binary version for ${bxiw_os_distrib_id} ${bxiw_os_distrib_release} 
usable with the Bayeux software suite.
EOF
 
    local _arch="amd64"
    local _bxjsontools_do_package=true
    local _bxjsontools_pkg_filename="bx${bxiw_package_name}_${bxiw_package_version}-${bxiw_pkg_release}_${_arch}.deb"
    if [ -f ${package_dir}/${_bxjsontools_pkg_filename} ]; then
	bxiw_log_info "Package '${_bxjsontools_pkg_filename}' exists in '${bxiw_package_dir}'."
	_bxjsontools_do_package=false
    fi
    local _bxjsontools_requires="\
		"
    _bxjsontools_requires_list=$(echo ${_bxjsontools_requires} | tr ' ' ',')
    _bxjsontools_conflicts_list="libbxjsontools-dev,libbxjsontools0.8"
    bxiw_log_info "Requires : ${_bxjsontools_requires_list}!"	
    if [ ${_bxjsontools_do_package} == true ]; then
	if [ "x${bxiw_os_arch}" != "xx86_64" ]; then
	    bxiw_log_error "Unsupported architecture ${bxiw_os_arch}!"	
	    return 1
	fi
	sudo checkinstall \
	     --type="debian" \
	     --install="no" \
	     --fstrans="no" \
	     --pkgname="bx${bxiw_package_name}" \
	     --pkgversion="${bxiw_package_version}" \
	     --pkgrelease=${bxiw_pkg_release} \
	     --pkglicense="MIT" \
	     --pkgsource="$(bxjsontools_installer_get_url ${bxiw_package_version})" \
	     --maintainer="${bxiw_pkg_maintener_email}" \
	     --provides="bx${bxiw_package_name}" \
	     --requires="${_bxjsontools_requires_list}" \
	     --conflicts="${_bxjsontools_conflicts_list}" \
	     --backup="no" \
	     --pakdir="${bxiw_package_dir}" \
	     --default \
	     ninja install
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Debian binary package build failed!"	
	    return 1
	fi
    fi	 
    return 0
}


function bxjsontools_installer_setup()
{
    bxiw_log_trace "bxjsontools_installer_setup: entering..."
    local _bxsoftware_setup_dir="${bxiw_setup_module_dir}"
    local _bxsoftware_setup_script_base="${_bxsoftware_setup_dir}/${bxiw_package_name}@${bxiw_package_version}.bash"
    local _bxsoftware_setup_script="${_bxsoftware_setup_script_base}"
    if [ -f ${_bxsoftware_setup_script} ]; then
	cp -f ${_bxsoftware_setup_script} ${_bxsoftware_setup_script}-save$(date -Isecond)
    fi
    local _bxsoftware_setup_script="${_bxsoftware_setup_dir}/${bxiw_package_name}@${bxiw_package_version}.bash"
    local _bxsoftware_underscored_version=$(bxiw_underscored_version ${bxiw_package_version})
    bxiw_log_info "Installing setup script '${_bxsoftware_setup_script}'..."
    cat ${bxiw_app_installer_prefix}/resources/package.bash.in | \
	sed \
	    -e "s@__PACKAGE_INSTALL_DIR__@${bxiw_install_dir}@g" \
	    -e "s@__PACKAGE_VERSION__@${bxiw_package_version}@g" \
	    -e "s@__PACKAGE_UVERSION__@${_bxsoftware_underscored_version}@g" \
	    > ${_bxsoftware_setup_script}
    return  0
}

bxiw_detect_os
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Unsupported OS!"
fi

bxiw_env
bxiw_parse_cl ${bxiw_app_cl_remaining_argv}
# bxiw_log_info "bxiw_app_cl_remaining_argv=${bxiw_app_cl_remaining_argv}"
bxjsontools_installer_parse_cl ${bxiw_app_cl_remaining_argv}
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Command line parse error!"
fi

bxjsontools_installer_prepare
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Preparation failed!"
fi

bxjsontools_installer_set_system_dependencies

bxjsontools_installer_print

bxiw_install_system_dependencies
if [ $? -ne 0 ]; then
    bxiw_exit 1 "System dependencies installation failed!"
fi

bxjsontools_installer_download
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Source archive download failed!"
fi

bxjsontools_installer_install
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Installation failed!"
fi

if [ ${bxiw_with_package} == false ]; then
    bxjsontools_installer_setup
    if [ $? -ne 0 ]; then
	bxiw_exit 1 "Setup failed!"
    fi
fi

bxiw_exit 0

# end
