#!/usr/bin/env bash

if [ ! -f "$(pwd)/.bxwi_bxdecay0.locate" ]; then
    echo >&2 "[error] Please run from the BxDecay0 installer directory!"
    exit 1
fi
source $(pwd)/../lib/libbxiw.bash
bxiw_app_name="bxdecay0_installer"
bxiw_app_saved_opwd=$(pwd)
bxiw_app_installer_prefix="$(pwd)"
bxiw_package_name="bxdecay0"
bxiw_default_package_version="1.1.2"
bxiw_supported_package_versions="1.0.9 1.0.10 1.0.11 1.0.12 1.1.0 1.1.2" 
bxiw_package_version=

gsl_root=
use_ninja=true
no_system_dependencies=false

function bxdecay0_installer_usage()
{
    cat<<EOF

bxdecay0_installer - BxDecay0 library installer

Synopsis:

    bxdecay0_installer [OPTION]...

Options:

  --help              Print this help then exit
EOF
    _bxiw_usage_options
    cat<<EOF
  --gsl-root path     Set teh GSL installation path
  --no-ninja          Do not use Ninja
EOF
     echo ""
    return 0
}


function bxdecay0_installer_parse_cl()
{
    while [ -n "$1" ]; do
	token="$1"
	if [ "x${token:0:1}" = "x-" ]; then
	    opt="${token}"
	    if [ ${opt} = "--help" ]; then
		bxdecay0_installer_usage
		bxiw_exit 0
	    elif [ ${opt} = "--gsl-root" ]; then
		shift 1
		gsl_root="$1"
	    elif [ ${opt} = "--no-ninja" ]; then
		use_ninja=false
	    elif [ ${opt} = "--no-system-dependencies" ]; then
		no_system_dependencies=true
	    else
		bxiw_log_error "Unsupported option '${opt}'!"
		return 1
	    fi
	else
	    arg="${token}"
	fi
	shift 1
    done
    return 0
}

function bxdecay0_installer_prepare()
{
    _bxiw_prepare_pre
 
    if [ ${bxiw_with_gui} = true ]; then
	
	local _do_rebuild_repr="FALSE"
	if [ ${bxiw_do_rebuild} = true ]; then
	    _do_rebuild_repr="TRUE"
	fi
	
	local _remove_build_dir_repr="FALSE"
	if [ ${bxiw_remove_build_dir} = true ]; then
	    _remove_build_dir_repr="TRUE"
	fi
	
	local _remove_tarballs_repr="FALSE"
	if [ ${bxiw_remove_tarballs} = true ]; then
	    _remove_tarballs_repr="TRUE"
	fi
	
	local _system_install_repr="FALSE"
	if [ ${bxiw_system_install} = true ]; then
	    _system_install_repr="TRUE"
	fi

	which yad > /dev/null 2>&1
	if [ $? -ne 0 ]; then
	    bxiw_message "[warning] yad is not installed! No GUI!"
	else
	    local _choices=$(yad --width=500 \
				 --form \
				 --title "${bxiw_package_name} installer options" \
				 --field="Cache directory:CDIR"   "${bxiw_cache_dir}" \
				 --field="Working directory:CDIR" "${bxiw_work_dir}" \
				 --field="Installation directory:CDIR" "${bxiw_install_dir}" \
				 --field="Force rebuild:CHK" "${_do_rebuild_repr}" \
				 --field="Remove build directory:CHK" "${_remove_build_dir_repr}" \
				 --field="Remove tarballs:CHK" "${_remove_tarballs_repr}" \
				 --field="System installation:CHK" "$_system_install_repr}" \
		  )
	    if [ "x${_choices}" = "x" ]; then
		bxiw_log_error "Cancelled dialog!"
		return 1
	    fi
	    bxiw_cache_dir=$(echo ${_choices} | cut -d'|' -f1)
	    bxiw_work_dir=$(echo ${_choices} | cut -d'|' -f2)
	    bxiw_install_dir=$(echo ${_choices} | cut -d'|' -f3)
	    _do_rebuild_repr=$(echo ${_choices} | cut -d'|' -f4)
	    if [ ${_do_rebuild_repr} == "TRUE" ]; then
		bxiw_do_rebuild=true
	    else
		bxiw_do_rebuild=false
	    fi
	    _remove_build_dir_repr=$(echo ${_choices} | cut -d'|' -f5)
	    if [ ${_remove_build_dir_repr} == "TRUE" ]; then
		bxiw_remove_build_dir=true
	    else
		bxiw_remove_build_dir=false
	    fi
	    _remove_tarballs_repr=$(echo ${_choices} | cut -d'|' -f6)
	    if [ ${_remove_tarballs_repr} == "TRUE" ]; then
		bxiw_remove_tarballs=true
	    else
		bxiw_remove_tarballs=false
	    fi
	    _system_install_repr=$(echo ${_choices} | cut -d'|' -f7)
	    if [ ${_system_install_repr} == "TRUE" ]; then
		bxiw_system_install=true
	    else
		bxiw_system_install=false
	    fi
	fi
    fi

    # GSL:
    if [ "x${gsl_root}" = "x" ]; then
	which gsl-config 2>&1 > /dev/null
	if [ $? -eq 0 ]; then
	    gsl_root="$(gsl-config --prefix)"
	else
	    gsl_root="/usr" # May work
	fi
    fi
    bxiw_log_info "Use GSL installation dir : '${gsl_root}'"
    
    if [ "x${gsl_root}" != "x" ]; then
	if [ ! -f "${gsl_root}/include/gsl/gsl_version.h" ]; then
	    bxiw_log_error "Cannot find '${gsl_root}/include/gsl/gsl_version.h' file!"
	    return 1
	fi
	bxiw_pass
    fi
    
    # Prepare:
    _bxiw_prepare_post
     
    return 0
}


function bxdecay0_installer_get_tarball()
{
    local _bxdecay0_version="$1"
    shift 1
    echo "bxdecay0-${_bxdecay0_version}.tar.gz"
    return 0
}


function bxdecay0_installer_get_url()
{
    local _bxdecay0_version="$1"
    local _bxdecay0_tarball=$(bxdecay0_installer_get_tarball ${_bxdecay0_version})
    echo "https://github.com/BxCppDev/bxdecay0/archive/${_bxdecay0_version}.tar.gz"
    ### https://github.com/IRCAD-IHU/bxdecay0
    return 0
}


function bxdecay0_installer_set_system_dependencies()
{
    
    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
	bxiw_system_packages_build="cmake \
        	    pkg-config \
        	    dpkg-dev \
       	    	    wget \
   		    g++ \
		    gcc \
		    libgsl-dev \
		    "
	if [ ${use_ninja} = true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} ninja-build"
	else
	    bxiw_system_packages_build="${bxiw_system_packages_build} make"
	fi
	if [ ${bxiw_with_package} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} checkinstall"
	fi
	if [ ${bxiw_with_gui} == true ]; then
	    bxiw_system_packages_build="${bxiw_system_packages_build} yad"
	fi
	# if [ "x${bxiw_os_distrib_release}" = "x18.04" ]; then
	    
	# fi
	bxiw_system_packages_run="g++ gcc"
	bxiw_pass
    elif [ "x${bxiw_os_distrib_id}" = "xCentOS" ]; then
	bxiw_pass
    elif [ "x${bxiw_os_distrib_id}" = "xScientific" ]; then
	bxiw_pass
    else
	bxiw_pass
    fi
    return 0
}


function bxdecay0_installer_print()
{
    bxiw_print
    bxiw_log_info "no_system_dependencies = ${no_system_dependencies}"
    return 0
}


function bxdecay0_installer_download()
{
    local _bxdecay0_tarball=$(bxdecay0_installer_get_tarball ${bxiw_package_version})
    local _bxdecay0_url=$(bxdecay0_installer_get_url ${bxiw_package_version})
    bxiw_log_info "BxDecay0 tarball : '${_bxdecay0_tarball}'"
    bxiw_log_info "BxDecay0 URL     : '${_bxdecay0_url}'"
    if [ ! -f ${bxiw_tag_downloaded} ]; then
	bxiw_download_file ${_bxdecay0_url} ${_bxdecay0_tarball}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Could not download the '${_bxdecay0_tarball}' file!"
	    return 1
	fi
	touch ${bxiw_tag_downloaded}
    else
	bxiw_log_info "BxDecay0 tarball is already downloaded."
    fi
    return  0
}


function bxdecay0_installer_install()
{
    local _bxdecay0_opwd=$(pwd)
    local _bxdecay0_tarball=$(bxdecay0_installer_get_tarball ${bxiw_package_version})
    cd ${bxiw_cache_dir}
    local _bxdecay0_source_dir="$(pwd)/bxdecay0-${bxiw_package_version}"
    bxiw_log_info "BxDecay0 version is                : '${bxiw_package_version}'"
    bxiw_log_info "BxDecay0 source directory is       : '${_bxdecay0_source_dir}'"
    if [ ! -d ${_bxdecay0_source_dir} ]; then
	bxiw_log_info "Unpacking source directory..."
	tar xzf ${bxiw_cache_dir}/${_bxdecay0_tarball}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Source directory has not been unpacked."
	    cd ${_bxdecay0_opwd}
	    return 1
	else
	    bxiw_log_info "Source directory has been unpacked."
	fi
    else
	bxiw_log_info "Source directory was already unpacked."
    fi

    # touch ${_bxdecay0_source_dir}/LICENSE.LGPL3.txt

    cd ${bxiw_build_dir}
    bxiw_log_info "BxDecay0 build directory is        : '${bxiw_build_dir}'"
    bxiw_log_info "BxDecay0 tag directory is          : '${bxiw_tag_dir}'"
    bxiw_log_info "BxDecay0 installation directory is : '${bxiw_install_dir}'"
    
    # Configuration:
    local _bxdecay0_do_config=false
    if [ ! -f ${bxiw_tag_configured} ]; then
	bxiw_log_info "BxDecay0 configuration is needed."
	_bxdecay0_do_config=true
    else
	bxiw_log_info "BxDecay0 configuration is already done."
	if [ ${bxiw_do_reconfigure} == true ]; then
	    bxiw_log_info "Forcing BxDecay0 reconfiguration..."
	    _bxdecay0_do_configure=true
	fi
    fi

    ninja_options=
    build_bin=make
    if [ ${use_ninja} = true ]; then
	ninja_options="-G Ninja"
	build_bin=ninja
    fi
    
    if [ ${_bxdecay0_do_config} == true ]; then
	bxiw_log_info "BxDecay0 configuration..."
	gsl_opt=
	if [ "x${gsl_root}" != "x" ]; then
	    gsl_opt="-DGSL_ROOT_DIR:PATH=${gsl_root}"
	fi
	cmake \
	    -DCMAKE_INSTALL_PREFIX:PATH="${bxiw_install_dir}" \
	    ${gsl_opt} \
	    ${ninja_options} \
	    ${_bxdecay0_source_dir}
	if [ $? -ne 0 ]; then
	    bxiw_log_error "BxDecay0 configuration failed!"
	    cd ${_bxdecay0_opwd}
	    return 1
	else
	    touch ${bxiw_tag_configured}
    	    bxiw_log_info "BxDecay0 is configured."
	fi
    else
	bxiw_log_info "Do not configure BxDecay0."
    fi
    
    # Build:
    local _bxdecay0_do_build=false
    if [ ! -f ${bxiw_tag_built} ]; then
	bxiw_log_info "BxDecay0 build is needed."
	_bxdecay0_do_build=true
    else
	bxiw_log_info "BxDecay0 build is already done."
	if [ ${bxiw_do_rebuild} == true ]; then
	    bxiw_log_info "Forcing BxDecay0 rebuild..."
	    _bxdecay0_do_build=true
	fi
    fi

    if [ ${_bxdecay0_do_build} == true ]; then
	bxiw_log_info "Building BxDecay0..."
	local _bxdecay0_nbprocs=${bxiw_nbprocs}
	if [ ${_bxdecay0_nbprocs} -gt 2 ]; then
	    let _bxdecay0_nbprocs=${bxiw_nbprocs}
	else
	    _bxdecay0_nbprocs=1 
	fi
	bxiw_log_info "#procs = ${_bxdecay0_nbprocs}"
	${build_bin} -j ${_bxdecay0_nbprocs}
	if [ $? -ne 0 ]; then
    	    bxiw_log_error "BxDecay0 build failed!"
    	    cd ${_bxdecay0_opwd}
    	    return 1
	else
	    touch ${bxiw_tag_built}
    	    bxiw_log_info "BxDecay0 is built."
	fi
    else
	bxiw_log_info "Do not build BxDecay0."
    fi

    # Installation:
    local _bxdecay0_do_install=false
    if [ ! -f ${bxiw_tag_installed} ]; then
	bxiw_log_info "BxDecay0 installation is needed."
	_bxdecay0_do_install=true
    else
	bxiw_log_info "BxDecay0 installation is already done."
	if [ ${bxiw_do_reinstall} == true ]; then
	    _bxdecay0_do_install=true
	    bxiw_log_info "Forcing BxDecay0 installation..."
	fi
    fi
    if [ ${bxiw_no_install} == true ]; then
	_bxdecay0_do_install=false
    fi

    if [ ${_bxdecay0_do_install} == true ]; then
	local _bxdecay0_do_package=false
	if [ ${bxiw_with_package} == true ]; then
	    _bxdecay0_do_package=true
	fi
	if [ ${_bxdecay0_do_package} == true ]; then
	    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
		bxiw_log_info "Building a binary package for BxDecay0..."
		bxdecay0_installer_makedebpack
	    else
    		bxiw_log_error "Cannot pack BxDecay0 for '${bxiw_os_distrib_id}'!"
    		cd ${_bxdecay0_opwd}
		return 1
	    fi
	else
	    bxiw_log_info "Installing BxDecay0..."
	    ${build_bin} install
	    if [ $? -ne 0 ]; then
    		bxiw_log_error "BxDecay0 installation failed!"
    		cd ${_bxdecay0_opwd}
    		return 1
	    else
		touch ${bxiw_tag_installed}
    		bxiw_log_info "BxDecay0 is installed."
	    fi
	fi
    else
	bxiw_log_info "Do not install BxDecay0."
    fi
    cd ${_bxdecay0_opwd}
    return  0
}


function bxdecay0_installer_makedebpack()
{
    local _bxdecay0_build_dir="${bxiw_build_dir}"
    cd ${_bxdecay0_build_dir}
    mkdir -p ${_bxdecay0_build_dir}/doc-pak
    touch ${_bxdecay0_build_dir}/description-pak
    cat>${_bxdecay0_build_dir}/description-pak<<EOF
BxDecay0 C++ Reflection Library (Bayeux edition)

This is a binary version for ${bxiw_os_distrib_id} ${bxiw_os_distrib_release} 
usable with the Bayeux software suite.
EOF
 
    local _arch="amd64"
    local _bxdecay0_do_package=true
    local _bxdecay0_pkg_filename="bx${bxiw_package_name}_${bxiw_package_version}-${bxiw_pkg_release}_${_arch}.deb"
    if [ -f ${package_dir}/${_bxdecay0_pkg_filename} ]; then
	bxiw_log_info "Package '${_bxdecay0_pkg_filename}' exists in '${bxiw_package_dir}'."
	_bxdecay0_do_package=false
    fi
    local _bxdecay0_requires="\
		"
    _bxdecay0_requires_list=$(echo ${_bxdecay0_requires} | tr ' ' ',')
    _bxdecay0_conflicts_list="libbxdecay0-dev,libbxdecay00.8"
    bxiw_log_info "Requires : ${_bxdecay0_requires_list}!"	
    if [ ${_bxdecay0_do_package} == true ]; then
	if [ "x${bxiw_os_arch}" != "xx86_64" ]; then
	    bxiw_log_error "Unsupported architecture ${bxiw_os_arch}!"	
	    return 1
	fi
	sudo checkinstall \
	     --type="debian" \
	     --install="no" \
	     --fstrans="no" \
	     --pkgname="bx${bxiw_package_name}" \
	     --pkgversion="${bxiw_package_version}" \
	     --pkgrelease=${bxiw_pkg_release} \
	     --pkglicense="MIT" \
	     --pkgsource="$(bxdecay0_installer_get_url ${bxiw_package_version})" \
	     --maintainer="${bxiw_pkg_maintener_email}" \
	     --provides="bx${bxiw_package_name}" \
	     --requires="${_bxdecay0_requires_list}" \
	     --conflicts="${_bxdecay0_conflicts_list}" \
	     --backup="no" \
	     --pakdir="${bxiw_package_dir}" \
	     --default \
	     ninja install
	if [ $? -ne 0 ]; then
	    bxiw_log_error "Debian binary package build failed!"	
	    return 1
	fi
    fi	 
    return 0
}


function bxdecay0_installer_setup()
{
    bxiw_log_trace "bxdecay0_installer_setup: entering..."
    bxiw_log_info "bxiw_setup_module_dir='${bxiw_setup_module_dir}'"
    local _bxsoftware_setup_dir="${bxiw_setup_module_dir}"
    local _bxsoftware_setup_script_base="${_bxsoftware_setup_dir}/${bxiw_package_name}@${bxiw_package_version}.bash"
    local _bxsoftware_setup_script="${_bxsoftware_setup_script_base}"
    if [ -f ${_bxsoftware_setup_script} ]; then
	cp -f ${_bxsoftware_setup_script} ${_bxsoftware_setup_script}-save$(date -Isecond)
    fi
    local _bxsoftware_setup_script="${_bxsoftware_setup_dir}/${bxiw_package_name}@${bxiw_package_version}.bash"
    local _bxsoftware_underscored_version=$(bxiw_underscored_version ${bxiw_package_version})
    bxiw_log_info "Installing setup script '${_bxsoftware_setup_script}'..."
    cat ${bxiw_app_installer_prefix}/resources/package.bash.in | \
	sed \
	    -e "s@__BXDECAY0_INSTALL_DIR__@${bxiw_install_dir}@g" \
	    -e "s@__BXDECAY0_VERSION__@${bxiw_package_version}@g" \
	    -e "s@__BXDECAY0_UVERSION__@${_bxsoftware_underscored_version}@g" \
	    > ${_bxsoftware_setup_script}
    return  0
}

bxiw_detect_os
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Unsupported OS!"
fi

bxiw_env
bxiw_parse_cl ${bxiw_app_cl_remaining_argv}
# bxiw_log_info "bxiw_app_cl_remaining_argv=${bxiw_app_cl_remaining_argv}"
bxdecay0_installer_parse_cl ${bxiw_app_cl_remaining_argv}
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Command line parse error!"
fi

bxdecay0_installer_prepare
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Preparation failed!"
fi

if [ ${no_system_dependencies} = false ]; then 

    bxdecay0_installer_set_system_dependencies

    bxiw_install_system_dependencies
    if [ $? -ne 0 ]; then
	bxiw_exit 1 "System dependencies installation failed!"
    fi
fi

bxdecay0_installer_print

bxdecay0_installer_download
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Source archive download failed!"
fi

bxdecay0_installer_install
if [ $? -ne 0 ]; then
    bxiw_exit 1 "Installation failed!"
fi

if [ ${bxiw_with_package} == false ]; then
    bxdecay0_installer_setup
    if [ $? -ne 0 ]; then
	bxiw_exit 1 "Setup failed!"
    fi
fi

bxiw_exit 0

# end
